spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automatic
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
#设置上传文件的路径
upload:
  location: D://upload


opencv:
  dll_path: D:\code\automatic (V2)\src\main\resources\lib\opencv_java452.dll